set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
#set_property BITSTREAM.CONFIG.CONFIGRATE 26 [current_design]
#set_property CONFIG_MODE SPIx4 [current_design]

set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


#set_property PACKAGE_PIN A13 [get_ports UA1_LOCK]
#set_property PACKAGE_PIN M22 [get_ports UA2_LOCK]
#set_property PACKAGE_PIN Y2 [get_ports UA3_LOCK]
#set_property PACKAGE_PIN U1 [get_ports UA4_LOCK]
#set_property IOSTANDARD LVCMOS33 [get_ports UA1_LOCK]
#set_property IOSTANDARD LVCMOS33 [get_ports UA2_LOCK]
#set_property IOSTANDARD LVCMOS33 [get_ports UA3_LOCK]
#set_property IOSTANDARD LVCMOS33 [get_ports UA4_LOCK]



#
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_1_data_p[2]}]
set_property PACKAGE_PIN AA18 [get_ports {TMDS_1_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_1_data_p[1]}]
set_property PACKAGE_PIN Y18 [get_ports {TMDS_1_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_1_data_p[0]}]
set_property PACKAGE_PIN V18 [get_ports {TMDS_1_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_1_clk_p]
set_property PACKAGE_PIN P15 [get_ports TMDS_1_clk_p]


#set_property PACKAGE_PIN A20 [get_ports {rxdata1[0]}]
#set_property PACKAGE_PIN A19 [get_ports {rxdata1[1]}]
#set_property PACKAGE_PIN B16 [get_ports {rxdata1[2]}]
#set_property PACKAGE_PIN A16 [get_ports {rxdata1[3]}]
#set_property PACKAGE_PIN B15 [get_ports {rxdata1[4]}]
#set_property PACKAGE_PIN A15 [get_ports {rxdata1[5]}]
#set_property PACKAGE_PIN D20 [get_ports {rxdata1[6]}]
#set_property PACKAGE_PIN D19 [get_ports {rxdata1[7]}]
#set_property PACKAGE_PIN C20 [get_ports {rxdata1[8]}]
#set_property PACKAGE_PIN C19 [get_ports {rxdata1[9]}]
#set_property PACKAGE_PIN E18 [get_ports {rxdata1[10]}]
#set_property PACKAGE_PIN C18 [get_ports {rxdata1[11]}]
#set_property PACKAGE_PIN D17 [get_ports {rxdata1[12]}]
#set_property PACKAGE_PIN C17 [get_ports {rxdata1[13]}]
#set_property PACKAGE_PIN D16 [get_ports {rxdata1[14]}]
#set_property PACKAGE_PIN E16 [get_ports {rxdata1[16]}]
#set_property PACKAGE_PIN C15 [get_ports {rxdata1[15]}]
#set_property PACKAGE_PIN D15 [get_ports {rxdata1[17]}]
#set_property PACKAGE_PIN C14 [get_ports {rxdata1[18]}]
#set_property PACKAGE_PIN D14 [get_ports {rxdata1[19]}]
#set_property PACKAGE_PIN C13 [get_ports {rxdata1[20]}]
#set_property PACKAGE_PIN E14 [get_ports {rxdata1[21]}]
##set_property PACKAGE_PIN F14 [get_ports {rxdata1[27]}]
##set_property PACKAGE_PIN E13 [get_ports {rxdata1[26]}]
##set_property PACKAGE_PIN F13 [get_ports {rxdata1[25]}]
##set_property PACKAGE_PIN G15 [get_ports {rxdata1[24]}]
#set_property PACKAGE_PIN H15 [get_ports {rxdata1[23]}]
#set_property PACKAGE_PIN J15 [get_ports {rxdata1[22]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {rxdata1[*]}]



#set_property PACKAGE_PIN H18 [get_ports {rxdata2[0]}]
#set_property PACKAGE_PIN G18 [get_ports {rxdata2[1]}]
##set_property PACKAGE_PIN H13 [get_ports {rxdata2[26]}]
##set_property PACKAGE_PIN J14 [get_ports {rxdata2[25]}]
##set_property PACKAGE_PIN G13 [get_ports {rxdata2[27]}]
#set_property PACKAGE_PIN H14 [get_ports {rxdata2[21]}]
#set_property PACKAGE_PIN J22 [get_ports {rxdata2[7]}]
#set_property PACKAGE_PIN H22 [get_ports {rxdata2[9]}]
#set_property PACKAGE_PIN K21 [get_ports {rxdata2[4]}]
#set_property PACKAGE_PIN K22 [get_ports {rxdata2[5]}]
#set_property PACKAGE_PIN L21 [get_ports {rxdata2[3]}]
#set_property PACKAGE_PIN J20 [get_ports {rxdata2[8]}]
#set_property PACKAGE_PIN J21 [get_ports {rxdata2[6]}]
##set_property PACKAGE_PIN K14 [get_ports {rxdata2[24]}]
#set_property PACKAGE_PIN A21 [get_ports {rxdata2[23]}]
#set_property PACKAGE_PIN F21 [get_ports {rxdata2[12]}]
#set_property PACKAGE_PIN G22 [get_ports {rxdata2[10]}]
#set_property PACKAGE_PIN G21 [get_ports {rxdata2[11]}]
#set_property PACKAGE_PIN D21 [get_ports {rxdata2[16]}]
#set_property PACKAGE_PIN E21 [get_ports {rxdata2[14]}]
#set_property PACKAGE_PIN D22 [get_ports {rxdata2[15]}]
#set_property PACKAGE_PIN E22 [get_ports {rxdata2[13]}]
#set_property PACKAGE_PIN B21 [get_ports {rxdata2[19]}]
#set_property PACKAGE_PIN B22 [get_ports {rxdata2[18]}]
#set_property PACKAGE_PIN C22 [get_ports {rxdata2[17]}]
#set_property PACKAGE_PIN B20 [get_ports {rxdata2[22]}]
#set_property PACKAGE_PIN F18 [get_ports {rxdata2[2]}]
#set_property PACKAGE_PIN F15 [get_ports {rxdata2[20]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {rxdata2[*]}]

#set_property PACKAGE_PIN F19 [get_ports {rxdata3[22]}]
#set_property PACKAGE_PIN F20 [get_ports {rxdata3[23]}]
##set_property PACKAGE_PIN H20 [get_ports {rxdata3[25]}]
##set_property PACKAGE_PIN G20 [get_ports {rxdata3[24]}]
##set_property PACKAGE_PIN H19 [get_ports {rxdata3[26]}]
#set_property PACKAGE_PIN K18 [get_ports {rxdata3[21]}]
##set_property PACKAGE_PIN K19 [get_ports {rxdata3[27]}]
#set_property PACKAGE_PIN L19 [get_ports {rxdata3[18]}]
#set_property PACKAGE_PIN L20 [get_ports {rxdata3[20]}]
#set_property PACKAGE_PIN M18 [get_ports {rxdata3[16]}]
#set_property PACKAGE_PIN L18 [get_ports {rxdata3[17]}]
#set_property PACKAGE_PIN N18 [get_ports {rxdata3[14]}]
#set_property PACKAGE_PIN N19 [get_ports {rxdata3[15]}]
#set_property PACKAGE_PIN M20 [get_ports {rxdata3[19]}]
#set_property PACKAGE_PIN L14 [get_ports {rxdata3[8]}]
#set_property PACKAGE_PIN L15 [get_ports {rxdata3[10]}]
#set_property PACKAGE_PIN L16 [get_ports {rxdata3[12]}]
#set_property PACKAGE_PIN M15 [get_ports {rxdata3[9]}]
#set_property PACKAGE_PIN M16 [get_ports {rxdata3[11]}]
#set_property PACKAGE_PIN M17 [get_ports {rxdata3[13]}]
#set_property PACKAGE_PIN AB1 [get_ports {rxdata3[0]}]
#set_property PACKAGE_PIN AB3 [get_ports {rxdata3[3]}]
#set_property PACKAGE_PIN AB2 [get_ports {rxdata3[1]}]
#set_property PACKAGE_PIN AA3 [get_ports {rxdata3[2]}]
#set_property PACKAGE_PIN AA5 [get_ports {rxdata3[5]}]
#set_property PACKAGE_PIN AB5 [get_ports {rxdata3[6]}]
#set_property PACKAGE_PIN AA4 [get_ports {rxdata3[4]}]
#set_property PACKAGE_PIN AA6 [get_ports {rxdata3[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {rxdata3[*]}]


set_property PACKAGE_PIN AA19 [get_ports {TMDS_0_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[2]}]
set_property PACKAGE_PIN AA20 [get_ports {TMDS_0_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[1]}]
set_property PACKAGE_PIN AB21 [get_ports {TMDS_0_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[0]}]
set_property PACKAGE_PIN W21 [get_ports TMDS_0_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_0_clk_p]


#set_property PACKAGE_PIN U20 [get_ports led_0]
#set_property IOSTANDARD LVCMOS33 [get_ports led_0]
#set_property PACKAGE_PIN U21 [get_ports led_1]
#set_property IOSTANDARD LVCMOS33 [get_ports led_1]

set_property PACKAGE_PIN Y7 [get_ports uart_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_rxd]
set_property PACKAGE_PIN AA8 [get_ports uart_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_txd]

#set_property PACKAGE_PIN A18 [get_ports pwrden1]
#set_property PACKAGE_PIN J17 [get_ports pwrden2]
#set_property PACKAGE_PIN AA1 [get_ports pwrden3]
#set_property PACKAGE_PIN B17 [get_ports rxclk1]
#set_property PACKAGE_PIN E19 [get_ports rxclk2]
#set_property PACKAGE_PIN J19 [get_ports rxclk3]
#set_property IOSTANDARD LVCMOS33 [get_ports pwrden1]
#set_property IOSTANDARD LVCMOS33 [get_ports pwrden2]
#set_property IOSTANDARD LVCMOS33 [get_ports pwrden3]
#set_property IOSTANDARD LVCMOS33 [get_ports rxclk1]
#set_property IOSTANDARD LVCMOS33 [get_ports rxclk2]
#set_property IOSTANDARD LVCMOS33 [get_ports rxclk3]


#set_property PACKAGE_PIN B18 [get_ports UF1_SEL]
#set_property PACKAGE_PIN N20 [get_ports UF2_SEL]
#set_property PACKAGE_PIN K17 [get_ports UF3_SEL]
#set_property IOSTANDARD LVCMOS33 [get_ports UF1_SEL]
#set_property IOSTANDARD LVCMOS33 [get_ports UF2_SEL]
#set_property IOSTANDARD LVCMOS33 [get_ports UF3_SEL]

# sda
set_property PACKAGE_PIN AB6 [get_ports {gpio_i2c_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_i2c_tri_io[0]}]
# scl
set_property PACKAGE_PIN AB7 [get_ports {gpio_i2c_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_i2c_tri_io[1]}]


#set_property PACKAGE_PIN T4 [get_ports uart_rxd]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
#set_property PACKAGE_PIN T5 [get_ports uart_txd]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
#set_property PACKAGE_PIN U5 [get_ports uart_txen]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_txen]

set_property IOSTANDARD LVCMOS33 [get_ports {qspi_flash_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io3_io]
set_property PACKAGE_PIN T19 [get_ports {qspi_flash_ss_io[0]}]
set_property PACKAGE_PIN P22 [get_ports qspi_flash_io0_io]
set_property PACKAGE_PIN R22 [get_ports qspi_flash_io1_io]
set_property PACKAGE_PIN P21 [get_ports qspi_flash_io2_io]
set_property PACKAGE_PIN R21 [get_ports qspi_flash_io3_io]