# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.cache/wt [current_project]
set_property parent.project_path /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/andy/zynq/repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0.xci
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_1/bd_2d50_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_2/bd_2d50_vsc_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_2/bd_2d50_vsc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_3/bd_2d50_hsc_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_3/bd_2d50_hsc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_4/bd_2d50_input_size_set_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_5/bd_2d50_ltr_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_5/bd_2d50_ltr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_6/bd_2d50_csc_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_6/bd_2d50_csc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_10/bd_2d50_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_11/bd_2d50_reset_sel_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_11/bd_2d50_reset_sel_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_11/bd_2d50_reset_sel_axis_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_12/bd_2d50_rst_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_12/bd_2d50_rst_axis_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_12/bd_2d50_rst_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_14/bd_2d50_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_15/bd_2d50_vdma_pad_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_16/bd_2d50_vdma_trunc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_17/bd_2d50_axi_vdma_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_17/bd_2d50_axi_vdma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_17/bd_2d50_axi_vdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_18/bd_2d50_reset_sel_axi_mm_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_18/bd_2d50_reset_sel_axi_mm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_18/bd_2d50_reset_sel_axi_mm_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_19/bd_2d50_rst_axi_mm_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_19/bd_2d50_rst_axi_mm_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_19/bd_2d50_rst_axi_mm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_20/bd_2d50_dint_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_20/bd_2d50_dint_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_21/bd_2d50_deint_ss_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_23/bd_2d50_deint_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_26/bd_2d50_vcr_i_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_26/bd_2d50_vcr_i_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_27/bd_2d50_vcr_o_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_27/bd_2d50_vcr_o_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_28/bd_2d50_hcr_0.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_28/bd_2d50_hcr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/bd_2d50_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_40/bd_2d50_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_40/bd_2d50_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_40/bd_2d50_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_41/bd_2d50_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_41/bd_2d50_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_41/bd_2d50_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_42/bd_2d50_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_42/bd_2d50_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_42/bd_2d50_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_43/bd_2d50_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_43/bd_2d50_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_43/bd_2d50_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_44/bd_2d50_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_44/bd_2d50_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_44/bd_2d50_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_45/bd_2d50_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_45/bd_2d50_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_45/bd_2d50_auto_cc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_46/bd_2d50_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_46/bd_2d50_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_46/bd_2d50_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_47/bd_2d50_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_47/bd_2d50_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_47/bd_2d50_auto_cc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_48/bd_2d50_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_48/bd_2d50_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_48/bd_2d50_auto_cc_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_49/bd_2d50_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_49/bd_2d50_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_49/bd_2d50_auto_cc_9_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_50/bd_2d50_auto_cc_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_50/bd_2d50_auto_cc_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_50/bd_2d50_auto_cc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_54/bd_2d50_auto_cc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_55/bd_2d50_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_56/bd_2d50_auto_ss_slid_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_57/bd_2d50_auto_cc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_29/bd_2d50_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_29/bd_2d50_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_30/bd_2d50_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_30/bd_2d50_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_31/bd_2d50_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_31/bd_2d50_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_51/bd_2d50_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_52/bd_2d50_auto_cc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_53/bd_2d50_auto_ss_slidr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_32/bd_2d50_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_32/bd_2d50_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_33/bd_2d50_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_33/bd_2d50_m05_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_34/bd_2d50_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_34/bd_2d50_m06_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_35/bd_2d50_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_35/bd_2d50_m07_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_36/bd_2d50_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_36/bd_2d50_m08_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_58/bd_2d50_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_58/bd_2d50_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_58/bd_2d50_auto_us_df_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_37/bd_2d50_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_37/bd_2d50_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_37/bd_2d50_auto_us_df_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_38/bd_2d50_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_38/bd_2d50_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_38/bd_2d50_auto_us_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1 -new_name system_v_proc_ss_0_0 -ip [get_ips system_v_proc_ss_0_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top system_v_proc_ss_0_0 -part xc7z020clg484-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix system_v_proc_ss_0_0_ system_v_proc_ss_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_v_proc_ss_0_0_stub.v
 lappend ipCachedFiles system_v_proc_ss_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_v_proc_ss_0_0_stub.vhdl
 lappend ipCachedFiles system_v_proc_ss_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_v_proc_ss_0_0_sim_netlist.v
 lappend ipCachedFiles system_v_proc_ss_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_v_proc_ss_0_0_sim_netlist.vhdl
 lappend ipCachedFiles system_v_proc_ss_0_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp system_v_proc_ss_0_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips system_v_proc_ss_0_0]
}

rename_ref -prefix_all system_v_proc_ss_0_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_v_proc_ss_0_0.dcp
create_report "system_v_proc_ss_0_0_synth_1_synth_report_utilization_0" "report_utilization -file system_v_proc_ss_0_0_utilization_synth.rpt -pb system_v_proc_ss_0_0_utilization_synth.pb"

if { [catch {
  file copy -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0.dcp /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0.dcp /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0_stub.v /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0_stub.vhdl /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0_sim_netlist.v /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.runs/system_v_proc_ss_0_0_synth_1/system_v_proc_ss_0_0_sim_netlist.vhdl /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.ip_user_files/ip/system_v_proc_ss_0_0]} {
  catch { 
    file copy -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.v /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.ip_user_files/ip/system_v_proc_ss_0_0
  }
}

if {[file isdir /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.ip_user_files/ip/system_v_proc_ss_0_0]} {
  catch { 
    file copy -force /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/system_v_proc_ss_0_0_stub.vhdl /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.ip_user_files/ip/system_v_proc_ss_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
