# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_21/bd_2d50_deint_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2d50_deint_ss_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/andy/zynq/play_zynq/tpg_vpss/tpg_vpss.srcs/sources_1/bd/system/ip/system_v_proc_ss_0_0/bd_0/ip/ip_21/bd_2d50_deint_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_2d50_deint_ss_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
