// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_2d50_hsc_0_hscale_core_polyphas (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        SrcImg_V_val_0_V_dout,
        SrcImg_V_val_0_V_empty_n,
        SrcImg_V_val_0_V_read,
        SrcImg_V_val_1_V_dout,
        SrcImg_V_val_1_V_empty_n,
        SrcImg_V_val_1_V_read,
        SrcImg_V_val_2_V_dout,
        SrcImg_V_val_2_V_empty_n,
        SrcImg_V_val_2_V_read,
        HwReg_Height_dout,
        HwReg_Height_empty_n,
        HwReg_Height_read,
        HwReg_WidthIn_dout,
        HwReg_WidthIn_empty_n,
        HwReg_WidthIn_read,
        HwReg_WidthOut_dout,
        HwReg_WidthOut_empty_n,
        HwReg_WidthOut_read,
        hfltCoeff_address0,
        hfltCoeff_ce0,
        hfltCoeff_q0,
        arrPhasesH_V_address0,
        arrPhasesH_V_ce0,
        arrPhasesH_V_q0,
        OutImg_V_val_0_V_din,
        OutImg_V_val_0_V_full_n,
        OutImg_V_val_0_V_write,
        OutImg_V_val_1_V_din,
        OutImg_V_val_1_V_full_n,
        OutImg_V_val_1_V_write,
        OutImg_V_val_2_V_din,
        OutImg_V_val_2_V_full_n,
        OutImg_V_val_2_V_write,
        HwReg_Height_out_din,
        HwReg_Height_out_full_n,
        HwReg_Height_out_write,
        HwReg_WidthOut_out_din,
        HwReg_WidthOut_out_full_n,
        HwReg_WidthOut_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state18 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] SrcImg_V_val_0_V_dout;
input   SrcImg_V_val_0_V_empty_n;
output   SrcImg_V_val_0_V_read;
input  [7:0] SrcImg_V_val_1_V_dout;
input   SrcImg_V_val_1_V_empty_n;
output   SrcImg_V_val_1_V_read;
input  [7:0] SrcImg_V_val_2_V_dout;
input   SrcImg_V_val_2_V_empty_n;
output   SrcImg_V_val_2_V_read;
input  [11:0] HwReg_Height_dout;
input   HwReg_Height_empty_n;
output   HwReg_Height_read;
input  [11:0] HwReg_WidthIn_dout;
input   HwReg_WidthIn_empty_n;
output   HwReg_WidthIn_read;
input  [11:0] HwReg_WidthOut_dout;
input   HwReg_WidthOut_empty_n;
output   HwReg_WidthOut_read;
output  [8:0] hfltCoeff_address0;
output   hfltCoeff_ce0;
input  [15:0] hfltCoeff_q0;
output  [11:0] arrPhasesH_V_address0;
output   arrPhasesH_V_ce0;
input  [8:0] arrPhasesH_V_q0;
output  [7:0] OutImg_V_val_0_V_din;
input   OutImg_V_val_0_V_full_n;
output   OutImg_V_val_0_V_write;
output  [7:0] OutImg_V_val_1_V_din;
input   OutImg_V_val_1_V_full_n;
output   OutImg_V_val_1_V_write;
output  [7:0] OutImg_V_val_2_V_din;
input   OutImg_V_val_2_V_full_n;
output   OutImg_V_val_2_V_write;
output  [11:0] HwReg_Height_out_din;
input   HwReg_Height_out_full_n;
output   HwReg_Height_out_write;
output  [11:0] HwReg_WidthOut_out_din;
input   HwReg_WidthOut_out_full_n;
output   HwReg_WidthOut_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg HwReg_Height_read;
reg HwReg_WidthIn_read;
reg HwReg_WidthOut_read;
reg hfltCoeff_ce0;
reg arrPhasesH_V_ce0;
reg HwReg_Height_out_write;
reg HwReg_WidthOut_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    SrcImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond9_i_i_reg_1635;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter2_reg;
reg   [0:0] tmp_60_i_i_reg_1653;
reg   [0:0] tmp_65_i_i_reg_1679;
reg    SrcImg_V_val_1_V_blk_n;
reg    SrcImg_V_val_2_V_blk_n;
reg    HwReg_Height_blk_n;
reg    HwReg_WidthIn_blk_n;
reg    HwReg_WidthOut_blk_n;
reg    OutImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter10;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter9_reg;
reg   [0:0] icmp3_reg_1644;
reg   [0:0] icmp3_reg_1644_pp0_iter9_reg;
reg   [0:0] or_cond1_i_i_reg_1693;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter9_reg;
reg    OutImg_V_val_1_V_blk_n;
reg    OutImg_V_val_2_V_blk_n;
reg    HwReg_Height_out_blk_n;
reg    HwReg_WidthOut_out_blk_n;
reg   [11:0] x_i_i_reg_589;
reg   [11:0] x_i_i_reg_589_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state7_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    SrcImg_V_val_0_V0_status;
reg    ap_predicate_op234_read_state10;
reg    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state11_pp0_stage0_iter4;
wire    ap_block_state12_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state14_pp0_stage0_iter7;
wire    ap_block_state15_pp0_stage0_iter8;
wire    ap_block_state16_pp0_stage0_iter9;
wire    OutImg_V_val_0_V1_status;
reg    ap_predicate_op275_write_state17;
reg    ap_block_state17_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] ReadEn_i_i_reg_601;
reg   [15:0] xReadPos_i_i_reg_612;
reg   [31:0] ReadEn_1_i_i_reg_623;
reg   [15:0] xReadPos_2_i_i_reg_637;
reg   [11:0] HwReg_Height_read_reg_1367;
reg    ap_block_state1;
reg   [11:0] HwReg_WidthIn_read_reg_1372;
reg   [11:0] HwReg_WidthOut_read_reg_1379;
wire   [11:0] TotalPixels_fu_691_p3;
reg   [11:0] TotalPixels_reg_1385;
wire    ap_CS_fsm_state2;
wire   [11:0] LoopSize_fu_697_p2;
reg   [11:0] LoopSize_reg_1390;
wire   [6:0] i_fu_709_p2;
reg   [6:0] i_reg_1398;
wire    ap_CS_fsm_state3;
wire   [9:0] tmp_6_fu_745_p2;
reg   [9:0] tmp_6_reg_1403;
wire   [0:0] exitcond6_i_i_fu_703_p2;
reg   [5:0] FiltCoeff_0_0_addr_reg_1408;
reg   [5:0] FiltCoeff_1_0_addr_reg_1413;
reg   [5:0] FiltCoeff_2_0_addr_reg_1418;
reg   [5:0] FiltCoeff_3_0_addr_reg_1423;
reg   [5:0] FiltCoeff_4_0_addr_reg_1428;
reg   [5:0] FiltCoeff_5_0_addr_reg_1433;
wire   [11:0] tmp_57_i_i_fu_751_p2;
reg   [11:0] tmp_57_i_i_reg_1603;
wire   [16:0] tmp_64_cast_i_i_fu_756_p1;
reg   [16:0] tmp_64_cast_i_i_reg_1608;
wire   [2:0] j_fu_765_p2;
reg   [2:0] j_reg_1616;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond8_i_i_fu_759_p2;
wire   [0:0] exitcond7_i_i_fu_785_p2;
wire    ap_CS_fsm_state6;
wire   [11:0] y_fu_790_p2;
reg   [11:0] y_reg_1630;
wire   [0:0] exitcond9_i_i_fu_796_p2;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter1_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter3_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter4_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter5_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter6_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter7_reg;
reg   [0:0] exitcond9_i_i_reg_1635_pp0_iter8_reg;
wire   [11:0] x_fu_801_p2;
reg   [11:0] x_reg_1639;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp3_fu_817_p2;
reg   [0:0] icmp3_reg_1644_pp0_iter1_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter2_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter3_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter4_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter5_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter6_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter7_reg;
reg   [0:0] icmp3_reg_1644_pp0_iter8_reg;
wire   [0:0] tmp_60_i_i_fu_840_p2;
wire   [0:0] icmp_fu_856_p2;
reg   [0:0] icmp_reg_1657;
wire   [0:0] tmp_65_i_i_fu_872_p2;
wire   [5:0] tmp_23_fu_877_p1;
reg   [5:0] tmp_23_reg_1683;
reg   [5:0] tmp_23_reg_1683_pp0_iter3_reg;
wire   [1:0] p_Result_6_i_i_fu_881_p4;
reg   [1:0] p_Result_6_i_i_reg_1688;
reg   [1:0] p_Result_6_i_i_reg_1688_pp0_iter3_reg;
wire   [0:0] or_cond1_i_i_fu_932_p2;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter3_reg;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter4_reg;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter5_reg;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter6_reg;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter7_reg;
reg   [0:0] or_cond1_i_i_reg_1693_pp0_iter8_reg;
reg   [7:0] OutPix_val_0_V_reg_1697;
reg   [7:0] OutPix_val_1_V_reg_1702;
reg   [7:0] OutPix_val_2_V_reg_1707;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter4;
reg    ap_condition_pp0_exit_iter3_state10;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg   [5:0] FiltCoeff_0_0_address0;
reg    FiltCoeff_0_0_ce0;
reg    FiltCoeff_0_0_we0;
wire   [15:0] FiltCoeff_0_0_q0;
reg   [5:0] FiltCoeff_1_0_address0;
reg    FiltCoeff_1_0_ce0;
reg    FiltCoeff_1_0_we0;
wire   [15:0] FiltCoeff_1_0_q0;
reg   [5:0] FiltCoeff_2_0_address0;
reg    FiltCoeff_2_0_ce0;
reg    FiltCoeff_2_0_we0;
wire   [15:0] FiltCoeff_2_0_q0;
reg   [5:0] FiltCoeff_3_0_address0;
reg    FiltCoeff_3_0_ce0;
reg    FiltCoeff_3_0_we0;
wire   [15:0] FiltCoeff_3_0_q0;
reg   [5:0] FiltCoeff_4_0_address0;
reg    FiltCoeff_4_0_ce0;
reg    FiltCoeff_4_0_we0;
wire   [15:0] FiltCoeff_4_0_q0;
reg   [5:0] FiltCoeff_5_0_address0;
reg    FiltCoeff_5_0_ce0;
reg    FiltCoeff_5_0_we0;
wire   [15:0] FiltCoeff_5_0_q0;
wire    grp_hscale_polyphase_fu_651_ap_start;
wire    grp_hscale_polyphase_fu_651_ap_done;
wire    grp_hscale_polyphase_fu_651_ap_idle;
wire    grp_hscale_polyphase_fu_651_ap_ready;
reg    grp_hscale_polyphase_fu_651_ap_ce;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_0_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_0_ce0;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_1_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_1_ce0;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_2_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_2_ce0;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_3_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_3_ce0;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_4_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_4_ce0;
wire   [5:0] grp_hscale_polyphase_fu_651_FiltCoeff_5_address0;
wire    grp_hscale_polyphase_fu_651_FiltCoeff_5_ce0;
wire   [7:0] grp_hscale_polyphase_fu_651_ap_return_0;
wire   [7:0] grp_hscale_polyphase_fu_651_ap_return_1;
wire   [7:0] grp_hscale_polyphase_fu_651_ap_return_2;
reg    ap_predicate_op266_call_state11;
reg    ap_predicate_op267_call_state12;
reg    ap_predicate_op268_call_state13;
reg    ap_predicate_op269_call_state14;
reg    ap_predicate_op270_call_state15;
wire    ap_block_state7_pp0_stage0_iter0_ignore_call34;
wire    ap_block_state8_pp0_stage0_iter1_ignore_call34;
wire    ap_block_state9_pp0_stage0_iter2_ignore_call34;
reg    ap_block_state10_pp0_stage0_iter3_ignore_call34;
wire    ap_block_state11_pp0_stage0_iter4_ignore_call34;
wire    ap_block_state12_pp0_stage0_iter5_ignore_call34;
wire    ap_block_state13_pp0_stage0_iter6_ignore_call34;
wire    ap_block_state14_pp0_stage0_iter7_ignore_call34;
wire    ap_block_state15_pp0_stage0_iter8_ignore_call34;
wire    ap_block_state16_pp0_stage0_iter9_ignore_call34;
reg    ap_block_state17_pp0_stage0_iter10_ignore_call34;
reg    ap_block_pp0_stage0_11001_ignoreCallOp266;
wire   [8:0] grp_reg_ap_uint_9_s_fu_834_ap_return;
reg    grp_reg_ap_uint_9_s_fu_834_ap_ce;
reg    ap_predicate_op141_call_state8;
wire    ap_block_state7_pp0_stage0_iter0_ignore_call28;
wire    ap_block_state8_pp0_stage0_iter1_ignore_call28;
wire    ap_block_state9_pp0_stage0_iter2_ignore_call28;
reg    ap_block_state10_pp0_stage0_iter3_ignore_call28;
wire    ap_block_state11_pp0_stage0_iter4_ignore_call28;
wire    ap_block_state12_pp0_stage0_iter5_ignore_call28;
wire    ap_block_state13_pp0_stage0_iter6_ignore_call28;
wire    ap_block_state14_pp0_stage0_iter7_ignore_call28;
wire    ap_block_state15_pp0_stage0_iter8_ignore_call28;
wire    ap_block_state16_pp0_stage0_iter9_ignore_call28;
reg    ap_block_state17_pp0_stage0_iter10_ignore_call28;
reg    ap_block_pp0_stage0_11001_ignoreCallOp141;
reg   [6:0] i_i_i_reg_555;
reg   [2:0] j_i_i_reg_566;
wire    ap_CS_fsm_state5;
reg   [11:0] y_i_i_reg_578;
wire    ap_CS_fsm_state18;
reg   [11:0] ap_phi_mux_x_i_i_phi_fu_593_p4;
reg   [31:0] ap_phi_mux_ReadEn_i_i_phi_fu_605_p4;
reg   [15:0] ap_phi_mux_xReadPos_i_i_phi_fu_616_p4;
wire   [31:0] ReadEn_fu_905_p1;
wire   [31:0] ap_phi_reg_pp0_iter2_ReadEn_1_i_i_reg_623;
wire   [15:0] p_xReadPos_i_i_fu_917_p3;
wire   [15:0] ap_phi_reg_pp0_iter2_xReadPos_2_i_i_reg_637;
reg    grp_hscale_polyphase_fu_651_ap_start_reg;
reg    ap_predicate_op266_call_state11_state10;
wire   [63:0] tmp_58_i_i_fu_715_p1;
wire  signed [63:0] tmp_7_cast_fu_780_p1;
wire   [63:0] tmp_67_i_i_fu_829_p1;
reg    SrcImg_V_val_0_V0_update;
reg    OutImg_V_val_0_V1_update;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] PixArray_0_val_0_V_1_fu_304;
wire   [7:0] PixArray_0_val_0_V_fu_1001_p3;
reg   [7:0] PixArray_0_val_1_V_1_fu_308;
wire   [7:0] PixArray_0_val_1_V_fu_1008_p3;
reg   [7:0] PixArray_0_val_2_V_1_fu_312;
wire   [7:0] PixArray_0_val_2_V_fu_1015_p3;
reg   [7:0] PixArray_1_val_0_V_1_fu_316;
wire   [7:0] PixArray_1_val_0_V_fu_1022_p3;
reg   [7:0] PixArray_1_val_1_V_1_fu_320;
wire   [7:0] PixArray_1_val_1_V_fu_1029_p3;
reg   [7:0] PixArray_1_val_2_V_1_fu_324;
wire   [7:0] PixArray_1_val_2_V_fu_1036_p3;
reg   [7:0] PixArray_2_val_0_V_1_fu_328;
wire   [7:0] PixArray_2_val_0_V_fu_1043_p3;
reg   [7:0] PixArray_2_val_1_V_1_fu_332;
wire   [7:0] PixArray_2_val_1_V_fu_1050_p3;
reg   [7:0] PixArray_2_val_2_V_1_fu_336;
wire   [7:0] PixArray_2_val_2_V_fu_1057_p3;
reg   [7:0] PixArray_3_val_0_V_1_fu_340;
wire   [7:0] PixArray_3_val_0_V_fu_1064_p3;
reg   [7:0] PixArray_3_val_1_V_1_fu_344;
wire   [7:0] PixArray_3_val_1_V_fu_1071_p3;
reg   [7:0] PixArray_3_val_2_V_1_fu_348;
wire   [7:0] PixArray_3_val_2_V_fu_1078_p3;
reg   [7:0] PixArray_4_val_0_V_1_fu_352;
wire   [7:0] PixArray_4_val_0_V_fu_1085_p3;
reg   [7:0] PixArray_4_val_1_V_1_fu_356;
wire   [7:0] PixArray_4_val_1_V_fu_1092_p3;
reg   [7:0] PixArray_4_val_2_V_1_fu_360;
wire   [7:0] PixArray_4_val_2_V_fu_1099_p3;
reg   [7:0] PixArray_5_val_0_V_1_fu_364;
wire   [7:0] PixArray_5_val_0_V_fu_1106_p3;
reg   [7:0] PixArray_5_val_1_V_1_fu_368;
wire   [7:0] PixArray_5_val_1_V_fu_1113_p3;
reg   [7:0] PixArray_5_val_2_V_1_fu_372;
wire   [7:0] PixArray_5_val_2_V_fu_1120_p3;
reg   [7:0] PixArray_6_val_0_V_fu_376;
reg   [7:0] PixArray_6_val_1_V_fu_380;
reg   [7:0] PixArray_6_val_2_V_fu_384;
reg   [7:0] PixArray_6_val_0_V_1_fu_388;
reg   [7:0] PixArray_6_val_1_V_1_fu_392;
reg   [7:0] PixArray_6_val_2_V_1_fu_396;
wire   [0:0] tmp_56_i_i_fu_687_p2;
wire   [7:0] tmp_5_fu_733_p3;
wire   [9:0] tmp_fu_725_p3;
wire   [9:0] p_shl1_cast_fu_741_p1;
wire   [9:0] tmp_59_i_i_cast_fu_771_p1;
wire   [9:0] tmp_7_fu_775_p2;
wire   [9:0] tmp_22_fu_807_p4;
wire   [11:0] xbySamples_fu_823_p2;
wire   [10:0] tmp_21_fu_846_p4;
wire   [16:0] tmp_62_cast_i_i_fu_862_p1;
wire   [16:0] tmp_63_i_i_fu_866_p2;
wire   [0:0] tmp_68_i_i_fu_899_p2;
wire   [15:0] xReadPos_fu_911_p2;
wire   [0:0] p_Result_7_i_i_fu_891_p3;
wire   [0:0] tmp_69_i_i_fu_927_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 grp_hscale_polyphase_fu_651_ap_start_reg = 1'b0;
end

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_0_0_address0),
    .ce0(FiltCoeff_0_0_ce0),
    .we0(FiltCoeff_0_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_0_0_q0)
);

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_1_0_address0),
    .ce0(FiltCoeff_1_0_ce0),
    .we0(FiltCoeff_1_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_1_0_q0)
);

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_2_0_address0),
    .ce0(FiltCoeff_2_0_ce0),
    .we0(FiltCoeff_2_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_2_0_q0)
);

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_3_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_3_0_address0),
    .ce0(FiltCoeff_3_0_ce0),
    .we0(FiltCoeff_3_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_3_0_q0)
);

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_4_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_4_0_address0),
    .ce0(FiltCoeff_4_0_ce0),
    .we0(FiltCoeff_4_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_4_0_q0)
);

bd_2d50_hsc_0_hscale_core_polyphas_FiltCoeff_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_5_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_5_0_address0),
    .ce0(FiltCoeff_5_0_ce0),
    .we0(FiltCoeff_5_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_5_0_q0)
);

bd_2d50_hsc_0_hscale_polyphase grp_hscale_polyphase_fu_651(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hscale_polyphase_fu_651_ap_start),
    .ap_done(grp_hscale_polyphase_fu_651_ap_done),
    .ap_idle(grp_hscale_polyphase_fu_651_ap_idle),
    .ap_ready(grp_hscale_polyphase_fu_651_ap_ready),
    .ap_ce(grp_hscale_polyphase_fu_651_ap_ce),
    .FiltCoeff_0_address0(grp_hscale_polyphase_fu_651_FiltCoeff_0_address0),
    .FiltCoeff_0_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_0_ce0),
    .FiltCoeff_0_q0(FiltCoeff_0_0_q0),
    .FiltCoeff_1_address0(grp_hscale_polyphase_fu_651_FiltCoeff_1_address0),
    .FiltCoeff_1_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_1_ce0),
    .FiltCoeff_1_q0(FiltCoeff_1_0_q0),
    .FiltCoeff_2_address0(grp_hscale_polyphase_fu_651_FiltCoeff_2_address0),
    .FiltCoeff_2_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_2_ce0),
    .FiltCoeff_2_q0(FiltCoeff_2_0_q0),
    .FiltCoeff_3_address0(grp_hscale_polyphase_fu_651_FiltCoeff_3_address0),
    .FiltCoeff_3_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_3_ce0),
    .FiltCoeff_3_q0(FiltCoeff_3_0_q0),
    .FiltCoeff_4_address0(grp_hscale_polyphase_fu_651_FiltCoeff_4_address0),
    .FiltCoeff_4_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_4_ce0),
    .FiltCoeff_4_q0(FiltCoeff_4_0_q0),
    .FiltCoeff_5_address0(grp_hscale_polyphase_fu_651_FiltCoeff_5_address0),
    .FiltCoeff_5_ce0(grp_hscale_polyphase_fu_651_FiltCoeff_5_ce0),
    .FiltCoeff_5_q0(FiltCoeff_5_0_q0),
    .PixArray_0_val_0_V_read(PixArray_0_val_0_V_1_fu_304),
    .PixArray_0_val_1_V_read(PixArray_0_val_1_V_1_fu_308),
    .PixArray_0_val_2_V_read(PixArray_0_val_2_V_1_fu_312),
    .PixArray_1_val_0_V_read(PixArray_1_val_0_V_1_fu_316),
    .PixArray_1_val_1_V_read(PixArray_1_val_1_V_1_fu_320),
    .PixArray_1_val_2_V_read(PixArray_1_val_2_V_1_fu_324),
    .PixArray_2_val_0_V_read(PixArray_2_val_0_V_1_fu_328),
    .PixArray_2_val_1_V_read(PixArray_2_val_1_V_1_fu_332),
    .PixArray_2_val_2_V_read(PixArray_2_val_2_V_1_fu_336),
    .PixArray_3_val_0_V_read(PixArray_3_val_0_V_1_fu_340),
    .PixArray_3_val_1_V_read(PixArray_3_val_1_V_1_fu_344),
    .PixArray_3_val_2_V_read(PixArray_3_val_2_V_1_fu_348),
    .PixArray_4_val_0_V_read(PixArray_4_val_0_V_1_fu_352),
    .PixArray_4_val_1_V_read(PixArray_4_val_1_V_1_fu_356),
    .PixArray_4_val_2_V_read(PixArray_4_val_2_V_1_fu_360),
    .PixArray_5_val_0_V_read(PixArray_5_val_0_V_1_fu_364),
    .PixArray_5_val_1_V_read(PixArray_5_val_1_V_1_fu_368),
    .PixArray_5_val_2_V_read(PixArray_5_val_2_V_1_fu_372),
    .PixArray_6_val_0_V_read(PixArray_6_val_0_V_fu_376),
    .PixArray_6_val_1_V_read(PixArray_6_val_1_V_fu_380),
    .PixArray_6_val_2_V_read(PixArray_6_val_2_V_fu_384),
    .PixArray_7_val_0_V_read(PixArray_6_val_0_V_1_fu_388),
    .PixArray_7_val_1_V_read(PixArray_6_val_1_V_1_fu_392),
    .PixArray_7_val_2_V_read(PixArray_6_val_2_V_1_fu_396),
    .PhasesH_0_read(tmp_23_reg_1683_pp0_iter3_reg),
    .ArrayIdx_read(p_Result_6_i_i_reg_1688_pp0_iter3_reg),
    .ap_return_0(grp_hscale_polyphase_fu_651_ap_return_0),
    .ap_return_1(grp_hscale_polyphase_fu_651_ap_return_1),
    .ap_return_2(grp_hscale_polyphase_fu_651_ap_return_2)
);

bd_2d50_hsc_0_reg_ap_uint_9_s grp_reg_ap_uint_9_s_fu_834(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .in_V(arrPhasesH_V_q0),
    .ap_return(grp_reg_ap_uint_9_s_fu_834_ap_return),
    .ap_ce(grp_reg_ap_uint_9_s_fu_834_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond9_i_i_fu_796_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter3_state10)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter2;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hscale_polyphase_fu_651_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op266_call_state11_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_hscale_polyphase_fu_651_ap_start_reg <= 1'b1;
        end else if ((grp_hscale_polyphase_fu_651_ap_ready == 1'b1)) begin
            grp_hscale_polyphase_fu_651_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp3_reg_1644_pp0_iter1_reg == 1'd1) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0))) begin
        ReadEn_1_i_i_reg_623 <= ap_phi_mux_ReadEn_i_i_phi_fu_605_p4;
    end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond1_i_i_fu_932_p2 == 1'd0) & (icmp3_reg_1644_pp0_iter1_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond1_i_i_fu_932_p2 == 1'd1) & (icmp3_reg_1644_pp0_iter1_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0)))) begin
        ReadEn_1_i_i_reg_623 <= ReadEn_fu_905_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ReadEn_1_i_i_reg_623 <= ap_phi_reg_pp0_iter2_ReadEn_1_i_i_reg_623;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0))) begin
        ReadEn_i_i_reg_601 <= ReadEn_1_i_i_reg_623;
    end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd0))) begin
        ReadEn_i_i_reg_601 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond8_i_i_fu_759_p2 == 1'd1))) begin
        i_i_i_reg_555 <= i_reg_1398;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_i_i_reg_555 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_i_i_reg_566 <= j_reg_1616;
    end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond6_i_i_fu_703_p2 == 1'd0))) begin
        j_i_i_reg_566 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp3_reg_1644_pp0_iter1_reg == 1'd1) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0))) begin
        xReadPos_2_i_i_reg_637 <= ap_phi_mux_xReadPos_i_i_phi_fu_616_p4;
    end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond1_i_i_fu_932_p2 == 1'd0) & (icmp3_reg_1644_pp0_iter1_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond1_i_i_fu_932_p2 == 1'd1) & (icmp3_reg_1644_pp0_iter1_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0)))) begin
        xReadPos_2_i_i_reg_637 <= p_xReadPos_i_i_fu_917_p3;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        xReadPos_2_i_i_reg_637 <= ap_phi_reg_pp0_iter2_xReadPos_2_i_i_reg_637;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0))) begin
        xReadPos_i_i_reg_612 <= xReadPos_2_i_i_reg_637;
    end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd0))) begin
        xReadPos_i_i_reg_612 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond9_i_i_reg_1635 == 1'd0))) begin
        x_i_i_reg_589 <= x_reg_1639;
    end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd0))) begin
        x_i_i_reg_589 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        y_i_i_reg_578 <= y_reg_1630;
    end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond6_i_i_fu_703_p2 == 1'd1))) begin
        y_i_i_reg_578 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond6_i_i_fu_703_p2 == 1'd0))) begin
        FiltCoeff_0_0_addr_reg_1408 <= tmp_58_i_i_fu_715_p1;
        FiltCoeff_1_0_addr_reg_1413 <= tmp_58_i_i_fu_715_p1;
        FiltCoeff_2_0_addr_reg_1418 <= tmp_58_i_i_fu_715_p1;
        FiltCoeff_3_0_addr_reg_1423 <= tmp_58_i_i_fu_715_p1;
        FiltCoeff_4_0_addr_reg_1428 <= tmp_58_i_i_fu_715_p1;
        FiltCoeff_5_0_addr_reg_1433 <= tmp_58_i_i_fu_715_p1;
        tmp_6_reg_1403[9 : 1] <= tmp_6_fu_745_p2[9 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Height_read_reg_1367 <= HwReg_Height_dout;
        HwReg_WidthIn_read_reg_1372 <= HwReg_WidthIn_dout;
        HwReg_WidthOut_read_reg_1379 <= HwReg_WidthOut_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LoopSize_reg_1390 <= LoopSize_fu_697_p2;
        TotalPixels_reg_1385 <= TotalPixels_fu_691_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp3_reg_1644_pp0_iter8_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter8_reg == 1'd0))) begin
        OutPix_val_0_V_reg_1697 <= grp_hscale_polyphase_fu_651_ap_return_0;
        OutPix_val_1_V_reg_1702 <= grp_hscale_polyphase_fu_651_ap_return_1;
        OutPix_val_2_V_reg_1707 <= grp_hscale_polyphase_fu_651_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0))) begin
        PixArray_0_val_0_V_1_fu_304 <= PixArray_0_val_0_V_fu_1001_p3;
        PixArray_0_val_1_V_1_fu_308 <= PixArray_0_val_1_V_fu_1008_p3;
        PixArray_0_val_2_V_1_fu_312 <= PixArray_0_val_2_V_fu_1015_p3;
        PixArray_1_val_0_V_1_fu_316 <= PixArray_1_val_0_V_fu_1022_p3;
        PixArray_1_val_1_V_1_fu_320 <= PixArray_1_val_1_V_fu_1029_p3;
        PixArray_1_val_2_V_1_fu_324 <= PixArray_1_val_2_V_fu_1036_p3;
        PixArray_2_val_0_V_1_fu_328 <= PixArray_2_val_0_V_fu_1043_p3;
        PixArray_2_val_1_V_1_fu_332 <= PixArray_2_val_1_V_fu_1050_p3;
        PixArray_2_val_2_V_1_fu_336 <= PixArray_2_val_2_V_fu_1057_p3;
        PixArray_3_val_0_V_1_fu_340 <= PixArray_3_val_0_V_fu_1064_p3;
        PixArray_3_val_1_V_1_fu_344 <= PixArray_3_val_1_V_fu_1071_p3;
        PixArray_3_val_2_V_1_fu_348 <= PixArray_3_val_2_V_fu_1078_p3;
        PixArray_4_val_0_V_1_fu_352 <= PixArray_4_val_0_V_fu_1085_p3;
        PixArray_4_val_1_V_1_fu_356 <= PixArray_4_val_1_V_fu_1092_p3;
        PixArray_4_val_2_V_1_fu_360 <= PixArray_4_val_2_V_fu_1099_p3;
        PixArray_5_val_0_V_1_fu_364 <= PixArray_5_val_0_V_fu_1106_p3;
        PixArray_5_val_1_V_1_fu_368 <= PixArray_5_val_1_V_fu_1113_p3;
        PixArray_5_val_2_V_1_fu_372 <= PixArray_5_val_2_V_fu_1120_p3;
        PixArray_6_val_0_V_fu_376 <= PixArray_6_val_0_V_1_fu_388;
        PixArray_6_val_1_V_fu_380 <= PixArray_6_val_1_V_1_fu_392;
        PixArray_6_val_2_V_fu_384 <= PixArray_6_val_2_V_1_fu_396;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_65_i_i_reg_1679 == 1'd1) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0))) begin
        PixArray_6_val_0_V_1_fu_388 <= SrcImg_V_val_0_V_dout;
        PixArray_6_val_1_V_1_fu_392 <= SrcImg_V_val_1_V_dout;
        PixArray_6_val_2_V_1_fu_396 <= SrcImg_V_val_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond9_i_i_reg_1635 <= exitcond9_i_i_fu_796_p2;
        exitcond9_i_i_reg_1635_pp0_iter1_reg <= exitcond9_i_i_reg_1635;
        icmp3_reg_1644_pp0_iter1_reg <= icmp3_reg_1644;
        x_i_i_reg_589_pp0_iter1_reg <= x_i_i_reg_589;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond9_i_i_reg_1635_pp0_iter2_reg <= exitcond9_i_i_reg_1635_pp0_iter1_reg;
        exitcond9_i_i_reg_1635_pp0_iter3_reg <= exitcond9_i_i_reg_1635_pp0_iter2_reg;
        exitcond9_i_i_reg_1635_pp0_iter4_reg <= exitcond9_i_i_reg_1635_pp0_iter3_reg;
        exitcond9_i_i_reg_1635_pp0_iter5_reg <= exitcond9_i_i_reg_1635_pp0_iter4_reg;
        exitcond9_i_i_reg_1635_pp0_iter6_reg <= exitcond9_i_i_reg_1635_pp0_iter5_reg;
        exitcond9_i_i_reg_1635_pp0_iter7_reg <= exitcond9_i_i_reg_1635_pp0_iter6_reg;
        exitcond9_i_i_reg_1635_pp0_iter8_reg <= exitcond9_i_i_reg_1635_pp0_iter7_reg;
        exitcond9_i_i_reg_1635_pp0_iter9_reg <= exitcond9_i_i_reg_1635_pp0_iter8_reg;
        icmp3_reg_1644_pp0_iter2_reg <= icmp3_reg_1644_pp0_iter1_reg;
        icmp3_reg_1644_pp0_iter3_reg <= icmp3_reg_1644_pp0_iter2_reg;
        icmp3_reg_1644_pp0_iter4_reg <= icmp3_reg_1644_pp0_iter3_reg;
        icmp3_reg_1644_pp0_iter5_reg <= icmp3_reg_1644_pp0_iter4_reg;
        icmp3_reg_1644_pp0_iter6_reg <= icmp3_reg_1644_pp0_iter5_reg;
        icmp3_reg_1644_pp0_iter7_reg <= icmp3_reg_1644_pp0_iter6_reg;
        icmp3_reg_1644_pp0_iter8_reg <= icmp3_reg_1644_pp0_iter7_reg;
        icmp3_reg_1644_pp0_iter9_reg <= icmp3_reg_1644_pp0_iter8_reg;
        or_cond1_i_i_reg_1693_pp0_iter3_reg <= or_cond1_i_i_reg_1693;
        or_cond1_i_i_reg_1693_pp0_iter4_reg <= or_cond1_i_i_reg_1693_pp0_iter3_reg;
        or_cond1_i_i_reg_1693_pp0_iter5_reg <= or_cond1_i_i_reg_1693_pp0_iter4_reg;
        or_cond1_i_i_reg_1693_pp0_iter6_reg <= or_cond1_i_i_reg_1693_pp0_iter5_reg;
        or_cond1_i_i_reg_1693_pp0_iter7_reg <= or_cond1_i_i_reg_1693_pp0_iter6_reg;
        or_cond1_i_i_reg_1693_pp0_iter8_reg <= or_cond1_i_i_reg_1693_pp0_iter7_reg;
        or_cond1_i_i_reg_1693_pp0_iter9_reg <= or_cond1_i_i_reg_1693_pp0_iter8_reg;
        p_Result_6_i_i_reg_1688_pp0_iter3_reg <= p_Result_6_i_i_reg_1688;
        tmp_23_reg_1683_pp0_iter3_reg <= tmp_23_reg_1683;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_1398 <= i_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond9_i_i_fu_796_p2 == 1'd0))) begin
        icmp3_reg_1644 <= icmp3_fu_817_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_60_i_i_fu_840_p2 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0))) begin
        icmp_reg_1657 <= icmp_fu_856_p2;
        tmp_65_i_i_reg_1679 <= tmp_65_i_i_fu_872_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_1616 <= j_fu_765_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp3_reg_1644_pp0_iter1_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0))) begin
        or_cond1_i_i_reg_1693 <= or_cond1_i_i_fu_932_p2;
        p_Result_6_i_i_reg_1688 <= {{grp_reg_ap_uint_9_s_fu_834_ap_return[7:6]}};
        tmp_23_reg_1683 <= tmp_23_fu_877_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond6_i_i_fu_703_p2 == 1'd1))) begin
        tmp_57_i_i_reg_1603 <= tmp_57_i_i_fu_751_p2;
        tmp_64_cast_i_i_reg_1608[11 : 0] <= tmp_64_cast_i_i_fu_756_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond9_i_i_reg_1635_pp0_iter1_reg == 1'd0))) begin
        tmp_60_i_i_reg_1653 <= tmp_60_i_i_fu_840_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_1639 <= x_fu_801_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_reg_1630 <= y_fu_790_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_0_0_address0 = FiltCoeff_0_0_addr_reg_1408;
    end else if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op266_call_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_0_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_0_address0;
    end else begin
        FiltCoeff_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_0_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op266_call_state11 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_0_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_0_ce0;
    end else begin
        FiltCoeff_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_i_i_reg_566 == 3'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_0_0_we0 = 1'b1;
    end else begin
        FiltCoeff_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_1_0_address0 = FiltCoeff_1_0_addr_reg_1413;
    end else if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_1_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_1_address0;
    end else begin
        FiltCoeff_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_1_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_1_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_1_ce0;
    end else begin
        FiltCoeff_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_i_i_reg_566 == 3'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_1_0_we0 = 1'b1;
    end else begin
        FiltCoeff_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_2_0_address0 = FiltCoeff_2_0_addr_reg_1418;
    end else if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_2_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_2_address0;
    end else begin
        FiltCoeff_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_2_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_op267_call_state12 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_2_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_2_ce0;
    end else begin
        FiltCoeff_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_i_i_reg_566 == 3'd2) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_2_0_we0 = 1'b1;
    end else begin
        FiltCoeff_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_3_0_address0 = FiltCoeff_3_0_addr_reg_1423;
    end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_3_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_3_address0;
    end else begin
        FiltCoeff_3_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_3_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_3_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_3_ce0;
    end else begin
        FiltCoeff_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_i_i_reg_566 == 3'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_3_0_we0 = 1'b1;
    end else begin
        FiltCoeff_3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_4_0_address0 = FiltCoeff_4_0_addr_reg_1428;
    end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_4_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_4_address0;
    end else begin
        FiltCoeff_4_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_4_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op268_call_state13 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_4_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_4_ce0;
    end else begin
        FiltCoeff_4_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((j_i_i_reg_566 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_4_0_we0 = 1'b1;
    end else begin
        FiltCoeff_4_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_5_0_address0 = FiltCoeff_5_0_addr_reg_1433;
    end else if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (ap_predicate_op270_call_state15 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_5_0_address0 = grp_hscale_polyphase_fu_651_FiltCoeff_5_address0;
    end else begin
        FiltCoeff_5_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_5_0_ce0 = 1'b1;
    end else if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (ap_predicate_op270_call_state15 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op269_call_state14 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        FiltCoeff_5_0_ce0 = grp_hscale_polyphase_fu_651_FiltCoeff_5_ce0;
    end else begin
        FiltCoeff_5_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((j_i_i_reg_566 == 3'd5) | ((j_i_i_reg_566 == 3'd6) | (j_i_i_reg_566 == 3'd7))))) begin
        FiltCoeff_5_0_we0 = 1'b1;
    end else begin
        FiltCoeff_5_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Height_blk_n = HwReg_Height_empty_n;
    end else begin
        HwReg_Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Height_out_blk_n = HwReg_Height_out_full_n;
    end else begin
        HwReg_Height_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Height_out_write = 1'b1;
    end else begin
        HwReg_Height_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_Height_read = 1'b1;
    end else begin
        HwReg_Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthIn_blk_n = HwReg_WidthIn_empty_n;
    end else begin
        HwReg_WidthIn_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthIn_read = 1'b1;
    end else begin
        HwReg_WidthIn_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthOut_blk_n = HwReg_WidthOut_empty_n;
    end else begin
        HwReg_WidthOut_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthOut_out_blk_n = HwReg_WidthOut_out_full_n;
    end else begin
        HwReg_WidthOut_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthOut_out_write = 1'b1;
    end else begin
        HwReg_WidthOut_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_WidthOut_read = 1'b1;
    end else begin
        HwReg_WidthOut_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OutImg_V_val_0_V1_update = 1'b1;
    end else begin
        OutImg_V_val_0_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (or_cond1_i_i_reg_1693_pp0_iter9_reg == 1'd1) & (icmp3_reg_1644_pp0_iter9_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        OutImg_V_val_0_V_blk_n = OutImg_V_val_0_V_full_n;
    end else begin
        OutImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (or_cond1_i_i_reg_1693_pp0_iter9_reg == 1'd1) & (icmp3_reg_1644_pp0_iter9_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        OutImg_V_val_1_V_blk_n = OutImg_V_val_1_V_full_n;
    end else begin
        OutImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (or_cond1_i_i_reg_1693_pp0_iter9_reg == 1'd1) & (icmp3_reg_1644_pp0_iter9_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        OutImg_V_val_2_V_blk_n = OutImg_V_val_2_V_full_n;
    end else begin
        OutImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SrcImg_V_val_0_V0_update = 1'b1;
    end else begin
        SrcImg_V_val_0_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_65_i_i_reg_1679 == 1'd1) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        SrcImg_V_val_0_V_blk_n = SrcImg_V_val_0_V_empty_n;
    end else begin
        SrcImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_65_i_i_reg_1679 == 1'd1) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        SrcImg_V_val_1_V_blk_n = SrcImg_V_val_1_V_empty_n;
    end else begin
        SrcImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_65_i_i_reg_1679 == 1'd1) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        SrcImg_V_val_2_V_blk_n = SrcImg_V_val_2_V_empty_n;
    end else begin
        SrcImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_condition_pp0_exit_iter3_state10 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter3_state10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_ReadEn_i_i_phi_fu_605_p4 = ReadEn_1_i_i_reg_623;
    end else begin
        ap_phi_mux_ReadEn_i_i_phi_fu_605_p4 = ReadEn_i_i_reg_601;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_xReadPos_i_i_phi_fu_616_p4 = xReadPos_2_i_i_reg_637;
    end else begin
        ap_phi_mux_xReadPos_i_i_phi_fu_616_p4 = xReadPos_i_i_reg_612;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond9_i_i_reg_1635 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_i_i_phi_fu_593_p4 = x_reg_1639;
    end else begin
        ap_phi_mux_x_i_i_phi_fu_593_p4 = x_i_i_reg_589;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        arrPhasesH_V_ce0 = 1'b1;
    end else begin
        arrPhasesH_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp266) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hscale_polyphase_fu_651_ap_ce = 1'b1;
    end else begin
        grp_hscale_polyphase_fu_651_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp141) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_reg_ap_uint_9_s_fu_834_ap_ce = 1'b1;
    end else begin
        grp_reg_ap_uint_9_s_fu_834_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hfltCoeff_ce0 = 1'b1;
    end else begin
        hfltCoeff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond6_i_i_fu_703_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond8_i_i_fu_759_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (exitcond7_i_i_fu_785_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) & ~((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_Height_out_din = HwReg_Height_dout;

assign HwReg_WidthOut_out_din = HwReg_WidthOut_dout;

assign LoopSize_fu_697_p2 = (TotalPixels_fu_691_p3 + 12'd4);

assign OutImg_V_val_0_V1_status = (OutImg_V_val_2_V_full_n & OutImg_V_val_1_V_full_n & OutImg_V_val_0_V_full_n);

assign OutImg_V_val_0_V_din = OutPix_val_0_V_reg_1697;

assign OutImg_V_val_0_V_write = OutImg_V_val_0_V1_update;

assign OutImg_V_val_1_V_din = OutPix_val_1_V_reg_1702;

assign OutImg_V_val_1_V_write = OutImg_V_val_0_V1_update;

assign OutImg_V_val_2_V_din = OutPix_val_2_V_reg_1707;

assign OutImg_V_val_2_V_write = OutImg_V_val_0_V1_update;

assign PixArray_0_val_0_V_fu_1001_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_1_val_0_V_1_fu_316);

assign PixArray_0_val_1_V_fu_1008_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_1_val_1_V_1_fu_320);

assign PixArray_0_val_2_V_fu_1015_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_1_val_2_V_1_fu_324);

assign PixArray_1_val_0_V_fu_1022_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_2_val_0_V_1_fu_328);

assign PixArray_1_val_1_V_fu_1029_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_2_val_1_V_1_fu_332);

assign PixArray_1_val_2_V_fu_1036_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_2_val_2_V_1_fu_336);

assign PixArray_2_val_0_V_fu_1043_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_3_val_0_V_1_fu_340);

assign PixArray_2_val_1_V_fu_1050_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_3_val_1_V_1_fu_344);

assign PixArray_2_val_2_V_fu_1057_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_3_val_2_V_1_fu_348);

assign PixArray_3_val_0_V_fu_1064_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_4_val_0_V_1_fu_352);

assign PixArray_3_val_1_V_fu_1071_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_4_val_1_V_1_fu_356);

assign PixArray_3_val_2_V_fu_1078_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_4_val_2_V_1_fu_360);

assign PixArray_4_val_0_V_fu_1085_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_5_val_0_V_1_fu_364);

assign PixArray_4_val_1_V_fu_1092_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_5_val_1_V_1_fu_368);

assign PixArray_4_val_2_V_fu_1099_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_5_val_2_V_1_fu_372);

assign PixArray_5_val_0_V_fu_1106_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_0_V_1_fu_388 : PixArray_6_val_0_V_fu_376);

assign PixArray_5_val_1_V_fu_1113_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_1_V_1_fu_392 : PixArray_6_val_1_V_fu_380);

assign PixArray_5_val_2_V_fu_1120_p3 = ((icmp_reg_1657[0:0] === 1'b1) ? PixArray_6_val_2_V_1_fu_396 : PixArray_6_val_2_V_fu_384);

assign ReadEn_fu_905_p1 = tmp_68_i_i_fu_899_p2;

assign SrcImg_V_val_0_V0_status = (SrcImg_V_val_2_V_empty_n & SrcImg_V_val_1_V_empty_n & SrcImg_V_val_0_V_empty_n);

assign SrcImg_V_val_0_V_read = SrcImg_V_val_0_V0_update;

assign SrcImg_V_val_1_V_read = SrcImg_V_val_0_V0_update;

assign SrcImg_V_val_2_V_read = SrcImg_V_val_0_V0_update;

assign TotalPixels_fu_691_p3 = ((tmp_56_i_i_fu_687_p2[0:0] === 1'b1) ? HwReg_WidthIn_read_reg_1372 : HwReg_WidthOut_read_reg_1379);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b0 == OutImg_V_val_0_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1)) | ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b0 == OutImg_V_val_0_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1)) | ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp141 = (((1'b0 == OutImg_V_val_0_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1)) | ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp266 = (((1'b0 == OutImg_V_val_0_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1)) | ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b0 == OutImg_V_val_0_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op275_write_state17 == 1'b1)) | ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op234_read_state10 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_WidthOut_out_full_n) | (1'b0 == HwReg_Height_out_full_n) | (1'b0 == HwReg_WidthOut_empty_n) | (1'b0 == HwReg_WidthIn_empty_n) | (1'b0 == HwReg_Height_empty_n) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter3 = ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_predicate_op234_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter3_ignore_call28 = ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_predicate_op234_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter3_ignore_call34 = ((1'b0 == SrcImg_V_val_0_V0_status) & (ap_predicate_op234_read_state10 == 1'b1));
end

assign ap_block_state11_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter4_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter4_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter5_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter5_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter7_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter7_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter8_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter8_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter9_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter9_ignore_call34 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_pp0_stage0_iter10 = ((1'b0 == OutImg_V_val_0_V1_status) & (ap_predicate_op275_write_state17 == 1'b1));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter10_ignore_call28 = ((1'b0 == OutImg_V_val_0_V1_status) & (ap_predicate_op275_write_state17 == 1'b1));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter10_ignore_call34 = ((1'b0 == OutImg_V_val_0_V1_status) & (ap_predicate_op275_write_state17 == 1'b1));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter0_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter0_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2_ignore_call28 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter2_ReadEn_1_i_i_reg_623 = 'bx;

assign ap_phi_reg_pp0_iter2_xReadPos_2_i_i_reg_637 = 'bx;

always @ (*) begin
    ap_predicate_op141_call_state8 = ((icmp3_reg_1644 == 1'd0) & (exitcond9_i_i_reg_1635 == 1'd0));
end

always @ (*) begin
    ap_predicate_op234_read_state10 = ((tmp_65_i_i_reg_1679 == 1'd1) & (tmp_60_i_i_reg_1653 == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op266_call_state11 = ((icmp3_reg_1644_pp0_iter3_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op266_call_state11_state10 = ((icmp3_reg_1644_pp0_iter2_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op267_call_state12 = ((icmp3_reg_1644_pp0_iter4_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op268_call_state13 = ((icmp3_reg_1644_pp0_iter5_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op269_call_state14 = ((icmp3_reg_1644_pp0_iter6_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op270_call_state15 = ((icmp3_reg_1644_pp0_iter7_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter7_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op275_write_state17 = ((or_cond1_i_i_reg_1693_pp0_iter9_reg == 1'd1) & (icmp3_reg_1644_pp0_iter9_reg == 1'd0) & (exitcond9_i_i_reg_1635_pp0_iter9_reg == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign arrPhasesH_V_address0 = tmp_67_i_i_fu_829_p1;

assign exitcond6_i_i_fu_703_p2 = ((i_i_i_reg_555 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond7_i_i_fu_785_p2 = ((y_i_i_reg_578 == HwReg_Height_read_reg_1367) ? 1'b1 : 1'b0);

assign exitcond8_i_i_fu_759_p2 = ((j_i_i_reg_566 == 3'd6) ? 1'b1 : 1'b0);

assign exitcond9_i_i_fu_796_p2 = ((ap_phi_mux_x_i_i_phi_fu_593_p4 == tmp_57_i_i_reg_1603) ? 1'b1 : 1'b0);

assign grp_hscale_polyphase_fu_651_ap_start = grp_hscale_polyphase_fu_651_ap_start_reg;

assign hfltCoeff_address0 = tmp_7_cast_fu_780_p1;

assign i_fu_709_p2 = (i_i_i_reg_555 + 7'd1);

assign icmp3_fu_817_p2 = ((tmp_22_fu_807_p4 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_856_p2 = ((tmp_21_fu_846_p4 == 11'd0) ? 1'b1 : 1'b0);

assign j_fu_765_p2 = (j_i_i_reg_566 + 3'd1);

assign or_cond1_i_i_fu_932_p2 = (tmp_69_i_i_fu_927_p2 & p_Result_7_i_i_fu_891_p3);

assign p_Result_6_i_i_fu_881_p4 = {{grp_reg_ap_uint_9_s_fu_834_ap_return[7:6]}};

assign p_Result_7_i_i_fu_891_p3 = grp_reg_ap_uint_9_s_fu_834_ap_return[9'd8];

assign p_shl1_cast_fu_741_p1 = tmp_5_fu_733_p3;

assign p_xReadPos_i_i_fu_917_p3 = ((tmp_68_i_i_fu_899_p2[0:0] === 1'b1) ? xReadPos_fu_911_p2 : ap_phi_mux_xReadPos_i_i_phi_fu_616_p4);

assign start_out = real_start;

assign tmp_21_fu_846_p4 = {{x_i_i_reg_589_pp0_iter1_reg[11:1]}};

assign tmp_22_fu_807_p4 = {{ap_phi_mux_x_i_i_phi_fu_593_p4[11:2]}};

assign tmp_23_fu_877_p1 = grp_reg_ap_uint_9_s_fu_834_ap_return[5:0];

assign tmp_56_i_i_fu_687_p2 = ((HwReg_WidthOut_read_reg_1379 < HwReg_WidthIn_read_reg_1372) ? 1'b1 : 1'b0);

assign tmp_57_i_i_fu_751_p2 = (TotalPixels_reg_1385 + 12'd5);

assign tmp_58_i_i_fu_715_p1 = i_i_i_reg_555;

assign tmp_59_i_i_cast_fu_771_p1 = j_i_i_reg_566;

assign tmp_5_fu_733_p3 = {{i_i_i_reg_555}, {1'd0}};

assign tmp_60_i_i_fu_840_p2 = ((ap_phi_mux_ReadEn_i_i_phi_fu_605_p4 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_62_cast_i_i_fu_862_p1 = ap_phi_mux_xReadPos_i_i_phi_fu_616_p4;

assign tmp_63_i_i_fu_866_p2 = (tmp_62_cast_i_i_fu_862_p1 + 17'd4);

assign tmp_64_cast_i_i_fu_756_p1 = HwReg_WidthIn_read_reg_1372;

assign tmp_65_i_i_fu_872_p2 = ((tmp_63_i_i_fu_866_p2 < tmp_64_cast_i_i_reg_1608) ? 1'b1 : 1'b0);

assign tmp_67_i_i_fu_829_p1 = xbySamples_fu_823_p2;

assign tmp_68_i_i_fu_899_p2 = ((p_Result_6_i_i_fu_881_p4 != 2'd0) ? 1'b1 : 1'b0);

assign tmp_69_i_i_fu_927_p2 = ((x_i_i_reg_589_pp0_iter1_reg < LoopSize_reg_1390) ? 1'b1 : 1'b0);

assign tmp_6_fu_745_p2 = (tmp_fu_725_p3 - p_shl1_cast_fu_741_p1);

assign tmp_7_cast_fu_780_p1 = $signed(tmp_7_fu_775_p2);

assign tmp_7_fu_775_p2 = (tmp_6_reg_1403 + tmp_59_i_i_cast_fu_771_p1);

assign tmp_fu_725_p3 = {{i_i_i_reg_555}, {3'd0}};

assign xReadPos_fu_911_p2 = (16'd1 + ap_phi_mux_xReadPos_i_i_phi_fu_616_p4);

assign x_fu_801_p2 = (ap_phi_mux_x_i_i_phi_fu_593_p4 + 12'd1);

assign xbySamples_fu_823_p2 = ($signed(12'd4092) + $signed(ap_phi_mux_x_i_i_phi_fu_593_p4));

assign y_fu_790_p2 = (y_i_i_reg_578 + 12'd1);

always @ (posedge ap_clk) begin
    tmp_6_reg_1403[0] <= 1'b0;
    tmp_64_cast_i_i_reg_1608[16:12] <= 5'b00000;
end

endmodule //bd_2d50_hsc_0_hscale_core_polyphas
